### ISSUE TITLE
Using owncloud8 the statistic site stays entirely white

### ISSUE THREAD

**Issue by Z3roCoder** [arnovr/ocusagecharts#80]
And nothing happens. I have the newest version of owncloud, and no error happens in the log files so I can sadly not say much to it

**Comment by arnovr** [comment]
If you did a clone, it is by design:
https://github.com/arnovr/ocusagecharts/wiki/Charts-not-visible,-error-500
You are probably missing the javascript library's.
My advise, download it from the official channel:
https://apps.owncloud.com/content/show.php/Storage+Usage+%2B+Activity+Charts?content=166746
